FROM node:22-alpine AS base 
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Prepare static files
FROM base AS build-front
COPY ./ ./
RUN npm install
RUN npm run build


# Release
FROM base AS release
COPY --from=build-front 
RUN cp -r ./dist ./server/public
RUN cd server && npm install

ENV PORT=1234
CMD ["node", "server/index.js"]


